format_version: 10
pipelines:
  tailor-ci:
    group: rust-docker
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-2d63dc6:
        git: https://github.com/guillheu/Tailor.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - server:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build-publish:
            timeout: 0
            environment_variables:
              DOCKERHUB_USERNAME: guillh
              TAILOR_SERVER_DOCKERHUB_REPO: guillh/tailor-server
              TAILOR_SERVER_IMAGE_TAG: 0.1.1
            secure_variables:
              DOCKERHUB_PWD: AES:w04x5iuEVQ52mFbieRIOgg==:smQHTdgtxTqx12hfSrnYNH4yIOWgIYtXJshgEy6pgKVHs1D3lulObt26uKVWMgMz
            tasks:
            - exec:
                arguments:
                - -c
                - docker build -t $TAILOR_SERVER_DOCKERHUB_REPO:$TAILOR_SERVER_IMAGE_TAG ./tailor-server
                command: /bin/sh
                run_if: passed
            - exec:
                arguments:
                - -c
                - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PWD
                command: /bin/sh
                run_if: passed
            - exec:
                arguments:
                - -c
                - docker push -t $TAILOR_SERVER_DOCKERHUB_REPO:$TAILOR_SERVER_IMAGE_TAG
                command: /bin/sh
                run_if: passed
